### ISSUE TITLE
Don't work with <base> tag

### ISSUE THREAD

**Issue by tsarma** [elboletaire/tabbedcontent#17] opened 2015-10-29 08:24 UTC
If you have a base tag in html, then switching a tab cuts off portion of url. Only base url + the Tab hash is shown in url.

**Comment by elboletaire** [comment] 2015-10-29 10:43
I even knew of the existence of this tag :sweat_smile: 

I'll take a look whenever I can :smile:

**Comment by elboletaire** [comment] 2015-12-01 18:24
Can you please add an example code on jsfiddle or something? I'm currently trying to reproduce it with no luck.

**Comment by elboletaire** [comment] 2015-12-16 10:20
@tsarma please, when you can...

**Comment by tsarma** [comment] 2015-12-16 12:12
Hi there, please see the site https://contao.org It uses base tag. Its a CMS, you can download and install locally.

**Comment by elboletaire** [comment] 2015-12-16 12:21
Really nice, but where are the tabs? Please send me a demo of the problem itself (a page where you have tabbedcontent configured and where fails due to the base tag).

**Comment by tsarma** [comment] 2015-12-17 07:52
Sorry I don't have a demo. It was then, I tried it locally on my machine using above mentioned CMS. As I was just looking for a simple tab menu, I switched to simple CSS method.

**Comment by elboletaire** [comment] 2015-12-17 14:49
Then tell me at least the section where you tried to put it, so I can test it on my own.

**Comment by tsarma** [comment] 2015-12-17 16:36
Mine is completely different content then what you have seen on http://contao.org. Contao is the CMS I was using and that CMS uses base tag. May be you can try on your own demo page. I have created a pull request here https://github.com/tsarma/tabbedcontent/commit/e7ff0bd4e2d0a7c53629c534ebce93cd1e25016d

**Comment by elboletaire** [comment] 2016-04-28 20:02
I think you have misunderstood how the `base` tag works. The example given by you in the PR #23 shows me that you added `base` as this:

~~~html
<base href="http://elboletaire.github.io/" />
~~~

That does not work, but it's logical because it's not correct. For my `demo.html` file the `base` tag should be:

~~~html
<base href="http://elboletaire.github.io/demos/demo.html" />
~~~

Or, if you prefer, you can set it as:

~~~html
<base href="http://elboletaire.github.io/demos/" />
~~~

And then define all the links like:

~~~html
<ul>
            <li><a href="demo.html#tab-1">Tab 1</a></li>
            <li><a href="demo.html#tab-2">Tab 2</a></li>
            <li><a href="demo.html#tab-3">Tab 3</a></li>
            <li><a href="demo.html#tab-n">Tab N</a></li>
            <li class="controls">
                <ul>
                    <li><a href="demo.html#prev">&lsaquo; Prev</a></li>
                    <li><a href="demo.html#next">Next &rsaquo;</a></li>
                </ul>
            </li>
</ul>
~~~

I close the issue at it works as expected using the `base` tag.

**Closed by elboletaire** 2016-04-28 20:02 UTC
Labels: enhancement
